### ISSUE TITLE
Multiple Routes with different Url found for given Controller 'Account' and Action 'Index'. Narrow down your selection

### ISSUE THREAD

**Issue by willapp** [Dresel/RouteLocalization#39]
I'm currently modifying our existing MVC application to use localized routes but am running into an issue with actions that have multiple routes and how to add translations for them. We have the following controller:

    [RoutePrefix("Account")]
    public class AccountController : BaseController
    {
        [Route, Route("Index")]
        public ActionResult Index()
        ...

The index action needs to work via both Account/ and Account/Index to be compatible with the existing application structure. However when adding a localized route:

    localization.ForCulture("fr-FR").ForController("Account", "MyApplication.Controllers").SetRoutePrefix("compte").ForAction("Index").AddTranslation("index");

I get the error `Multiple Routes with different Url found for given Controller 'Account' and Action 'Index'. Narrow down your selection` but I'm not sure how to solve this? Is using named routes the only way?

**Comment by Dresel** [comment]
Yes this currently only work with named routes. If you have a better idea how this use case could be handled I'm open for ideas.

**Comment by willapp** [comment]
Okay I thought that might be the case. Just wanted confirmation before I start naming these routes in case there was another way.

**Comment by willapp** [comment]
Just to clarify for those following a similar path. We ended up deciding that using named routes for all localizable route entries was the simplest way of implementing this. By giving each route a unique name (which you have to anyway) - even those which correspond to the same action - you can avoid this error entirely.

**Comment by Dresel** [comment]
So you use named routes also for actions that have only one route applied?

**Comment by willapp** [comment]
Yes. We've set up a framework where the localized routes are driven by resource files within the site, so on app startup we pull the localized resources for each supported culture (driven by configuration) and for each language we loop the resource entries using the key as the named route and the value as the localized URL. Seems to work quite nicely so far, but it's still in development at the moment so hasn't been tested in the wild yet.

**Comment by Dresel** [comment]
Ok this makes sense - when translating via resource / database it is the easiest way to use named routes instead of storing controller / action names (although using named routes for every route is a bit of an overhead).

**Comment by karanjamwal** [comment]
Hi,

I am getting same error when I am trying set translation for Action method which has parameters.
Please let me know how we can set translation for action methods which has parameters. In sample project, T4MVC templates are used and I want to avoid using those template.

Regards,

Karan

**Comment by Dresel** [comment]
If you use two Attribute Routes for one Action, the easiest way would be to use NamedRoutes.

If you use two Attribute Routes for two Actions with the same name but different parameters, you can use the parameters parameter.

See [distinguish overloaded actions by parameters](https://github.com/Dresel/RouteLocalization/blob/master/Documentation/SelectingAndTranslatingRoutes.md#distinguish-overloaded-actions-by-parameters).

**Comment by karanjamwal** [comment]
Thank you. It worked for me. I am using NamedRoute for these special cases
