### ISSUE TITLE
Unit testability of Localization

### ISSUE THREAD

**Issue by gretro** [Dresel/RouteLocalization#43]
I started creating an attribute-based translation system on top of our controllers, but I'm unable to have it unit tested because the classes are not abstracted with interfaces or abstract classes. It would be great to be able to mock or fake the localization classes, including the RouteTranslator objects.

**Comment by Dresel** [comment]
Sorry for my late replay - I was on vacation. Sounds like a good idea. Please feel free to submit a Merge Request with you suggested changes.
