### ISSUE TITLE
AddAsNeutralRouteAndReplaceByFirstTranslation, two cultures, one default

### ISSUE THREAD

**Issue by brgrz** [Dresel/RouteLocalization#44]
When using `AddAsNeutralRouteAndReplaceByFirstTranslation` the empty route gets removed within `RouteTranslator`. This prevents me from having a default empty root atribute route.

My setup is default culture = "en", allowed cultures is "en, sl" and my neutral attribute routes are actually all "en" - that way, by default, if there is only english supported, I don't have to add "en" localizations.

However, I think this removes the empty route from the route table:

			if (Configuration.AttributeRouteProcessing == AttributeRouteProcessing.AddAsNeutralRouteAndReplaceByFirstTranslation)
			{
				// Remove neutral route
				route.RemoveTranslation(string.Empty);
			}

What was the reasoning behind this?

If I comment this out my site works, empty root route loading the correct controller/view.

**Comment by Dresel** [comment]
Why do you use `AddAsNeutralRouteAndReplaceByFirstTranslation ` anyway? Seems you want use AddAsDefaultCultureRoute / AddAsNeutralAndDefaultCultureRoute? Refer to https://github.com/Dresel/RouteLocalization/blob/master/Documentation/TheConfigurationClass.md please.

**Comment by brgrz** [comment]
Hey Christopher,

what I have is a bunch of attribute routes which are in English and my default culture is also set to "en".

However, what I want in one specific case is to override these routes with a different culture routes (translated) and it is only one culture that is in use. So I want to have those routes set up as English attribute routes by default but I use the same app on multiple projects and in some projects I might use another language and by that I mean only one language.

Every other option would leave the default English attribute routes around and the same content will be accessible via two routes which violates some Google (and other search engine) best practices.

So what I thought to do was this

`const string defaultCulture = "en";
ISet<string> acceptedCultures = new HashSet<string>() { defaultCulture, "sl-si" };`

and then use 

`configuration.DefaultCulture = defaultCulture;
configuration.AcceptedCultures = acceptedCultures;
configuration.AttributeRouteProcessing = AttributeRouteProcessing.AddAsNeutralRouteAndReplaceByFirstTranslation;
configuration.AddCultureAsRoutePrefix = true;`

to replace those English routes with just the sl-si ones (which are defined within translations setup).

That is where I ran into issues with `AddAsNeutralRouteAndReplaceByFirstTranslation` because it doesn't seem to work, it actually did not register any route for the route in question (neither default English one nor the translated one).

**Comment by Dresel** [comment]
Well `AddAsNeutralRouteAndReplaceByFirstTranslation` actually register routes, but "neutral" ones. What you would need is something like `AddAsDefaultCultureRouteAndReplaceByFirstTranslation` if I understand you correctly?

I plan to simplify the API for the next version (maybe when migrating to MVC 6), but for now you could create your own ExtensionMethod like this:

    public static void ReplaceDefaultTranslation<T>(this RouteTranslator<T> localization, string url)
    {
        LocalizationCollectionRoute localizationCollectionRoute = localization.GetRoutes().Single();
        localizationCollectionRoute.RemoveTranslation(localization.Configuration.DefaultCulture);

        localization.AddTranslation(url);
    }

... and call this instead of AddTranslation:

    localization.ForCulture("de")
        .ForController<AccountController>()
        .ForAction(x => x.Login())
        .ReplaceDefaultTranslation("Einloggen");

Does this help you?

**Comment by brgrz** [comment]
It is not working for me because it seems it tries to remove the default culture route but I'm currently registering with AddAsNeutralRoute (as said AddAsNeutralRouteAndReplaceByFirstTranslation did not work, btw why is that?). Apparently there are only neutral routes in my route table and as such the above `ReplaceDefaultTranslation` does nothing (I did debug, it went through but changed nothing).

I am begining to think I have some issues with some of the routes in my app but still the RouteLocalization does not work as expected.

My app basically has some neutral routes that will never get translated, some default English routes that we also won't translate and some English routes that most likely will get translated.

As I am registering with AddAsNeutralRoute most of the stuff works out-of-the-box but special cases where I need to replace the neutral route with a translated one do not (which is why AddAsNeutralRouteAndReplaceByFirstTranslation is perfect for me but sadly it is not working).

**Comment by brgrz** [comment]
Another thing - I'm using `AddAsNeutralRoute` because certain routes don't get registered when using `AddAsDefaultRoute` (though I am not sure which is better suited for an app that has routes as mixed as described in my previous comment).

For instance this route does not get registered when using `AddAsDefaultRoute`:

	//[RoutePrefix("pages")]
    public partial class ContentPageController : BaseController

		[Route("~/{id:int?}/{slug?}", Order=0)]
		public virtual ActionResult Display(int id = 0, string slug = "", string culture = "")

I intentionally left the commented RoutePrefix in there to further emphasize that this is a route without prefix (also neutral by default) but should be later registered as culture route (pages always have culture so URLs end up being /en/363/some-content-page).

This route does get registered when using ˙AddAsNeutralRoute`.

**Comment by brgrz** [comment]
We could discuss this over Skype and we could also discuss the next version (I did not notice anything new coming from Microsoft in MVC 6 with regards to route localization).

**Comment by brgrz** [comment]
There's mostly one thing that bothers me and it is whether we actually need all three concepts in RL: neutral, default and translated routes. Especially the first two are delicate and can maybe be simplified (when there's only one culture it is default OOB, implictly). Propagate neutral routes to default culture routes by default. That way we can dump the concept of neutral routes.

**Comment by Dresel** [comment]
I don't get you.

When you use AddAsNeutralRoute or AddAsDefaultCultureRouteAndReplaceByFirstTranslation every attribute route will be added as neutral route.

They only difference between them is that if you add an translation, AddAsDefaultCultureRouteAndReplaceByFirstTranslation removes an existing neutral route. If you do want both routes, don't use AddAsDefaultCultureRouteAndReplaceByFirstTranslation.

To manually do that modify the example from above to

    public static void ReplaceNeutralTranslation<T>(this RouteTranslator<T> localization, string url)
    {
        LocalizationCollectionRoute localizationCollectionRoute = localization.GetRoutes().Single();
        localizationCollectionRoute.RemoveTranslation(string.Empty);

        localization.AddTranslation(url);
    }

If this doesn't help you, please provide a little example with code (one controller, 2-3 actions / routes) and your configuration - explain what you would expect and what you get.

**Comment by brgrz** [comment]
Ok, here is one example:

Using AddAsNeutralAndReplaceByFirstTranslation does not register the following route or it's translated counterpart:

//[RoutePrefix("pages")]
public partial class ContentPageController : BaseController

    [Route("~/{id:int?}/{slug?}", Order=0)]
    public virtual ActionResult Display(int id = 0, string slug = "", string culture = "")

Here is the translation registration:

			localization.ForCulture("sl-si")
				.ForController<ContentPageController>()
				.ForAction(x => x.Display(0, "", ""), new Type[] { typeof(Int32), typeof(String), typeof(string) })
				.AddTranslation("{id}/{slug}");

**Comment by Dresel** [comment]
I'm using the Sample Project from the GitHub Project. I added your action to HomeController:

    [Route("~/{id:int?}/{slug?}", Order = 0)]
    public virtual ActionResult Display(int id = 0, string slug = "", string culture = "")
    {
        return Content("It works!");
    }

I changed the configuration to

    configuration.AttributeRouteProcessing = AttributeRouteProcessing.AddAsNeutralRouteAndReplaceByFirstTranslation;

And added

    localization.ForCulture("de")
        .ForController<HomeController>()
        .ForAction(x => x.Display(0, string.Empty, string.Empty), new[] { typeof(int), typeof(string), typeof(string) })
        .AddTranslation("~/{id}/{slug}"); // I use ~ to keep it the same as above

I can now access "/de/1/something".

If this does not work for you, can you check which routes are registered instead - e.g. with https://github.com/Dresel/Glimpse.RouteLocalization.

**Comment by brgrz** [comment]
Yes, the routes in the format you mentioned do work, it is the root route (empty) that does not and it should. Can you check if it works for you?

**Comment by Dresel** [comment]
Depends on what you mean with does not work.

The action should

	[Route]
	public virtual ActionResult Start()
	{
		// Redirect to localized Index
		return RedirectToAction(MVC.Home.Index().AddRouteValues(new { culture = Thread.CurrentThread.CurrentCulture.Name }));
	}

always be called.

But when changing to `AttributeRouteProcessing.AddAsNeutralRouteAndReplaceByFirstTranslation` there are now only neutral routes or translated routes (de), but no more english (en) routes.

When Thread.CurrentThread.CurrentCulture.Name is en you will get an "No route in the route table matches the supplied values." error.

**Comment by brgrz** [comment]
By working, I mean that it hits the above action (not the Start() one which you just added but the Display() one) which in my case should work either when culture is supplied or when it's not.

**Comment by Dresel** [comment]
The Start action is part of the sample project. I will try without.

**Comment by Dresel** [comment]
Now I understand what you mean. If you use use `configuration.AddCultureAsRoutePrefix = true` it is applied to the route and therefore mandatory.

If you want a root route, you need a neutral route.

**Comment by brgrz** [comment]
Ok, I understand. I don't mind having both neutral and translated route for this route but I do mind it for some other routes where only translated would suffice (and where two routes to the same content would mean trouble in terms of SEO). So I guess the solution is to use your proposed custom replace solution.

Now that I think of it maybe that handling should be moved to route translations altogether rather than have one universal setting/convention in the config.

**Comment by brgrz** [comment]
I managed to solve my issue with the help of those two static methods.
