### ISSUE TITLE
Home page route (root empty route) issues

### ISSUE THREAD

**Issue by brgrz** [Dresel/RouteLocalization#46]
I'm having constant issues with the root route in my applications. My web apps use both variants of route translation registration (neutral and default) - not both in one app but different across apps.

The issue with default in combination with 'addcultureprefix' setting is that it modifies my Home route - this would be the one that listens at http://domain.com/. RL modifies it to http://domain.com/en.

If I use neutral this doesn't happen but then culture prefixes are gone for all the routes (which I don't want).

What is the best way to tell RL to leave this one route alone or to remove it and bring back the original root route as specified in my controller with attribute routing?

I tried doing this

```
public static void RemoveDefaultRouteTranslation<T>(this RouteTranslator<T> localization)
{
    var localizationCollectionRoute = localization.GetRoutes().Single();
    localizationCollectionRoute.RemoveTranslation(localization.Configuration.DefaultCulture);
    // localization.AddTranslation("~/");
    }
```

or with the last line uncommented and it didn't work in any case.

**Comment by Dresel** [comment]
Do you want to add an neutral route or an localized route with no prefix? Neutral routes can be added via the localization object (https://github.com/Dresel/RouteLocalization/blob/master/Documentation/SelectingAndTranslatingRoutes.md#adding-neutral-routes):

    localization
        .ForController<HomeController>()
        .ForAction(x => x.Index())
        .AddNeutralTranslation();

... or when working with the route itself via string.Empty for the culture parameter:

    localizationCollectionRoute.AddTranslation(string.Empty, string.Empty);

If you instead want the route localized you can call AddTranslation on the route itself like this;

    localizationCollectionRoute.AddTranslation(string.Empty, localization.Configuration.DefaultCulture);

**Comment by brgrz** [comment]
If I do this 

			// this is mandatory to bring back the root (~/) route which RL translated to ~/en
			localization.ForCulture(localization.Configuration.DefaultCulture)
				.ForController<ContentPageController>()
				.ForAction(x=>x.Home())
				.RemoveDefaultRouteTranslation();

		public static void RemoveDefaultRouteTranslation<T>(this RouteTranslator<T> localization)
		{
			var localizationCollectionRoute = localization.GetRoutes().Single();
			localizationCollectionRoute.RemoveTranslation(localization.Configuration.DefaultCulture);
			localization.AddNeutralTranslation();
		}

then the translated root route is removed and the neutral one gets added but since I am manually removing and adding routes it messes up the order (which I set with Order parameter on attribute routes) and as such certain things break.

I'm starting to think we need a way to completely exclude certain attribute routes from RL even touching them.

We could do that by marking those actions with some specific attribute which RL would honor.

Is there another way?

**Comment by Dresel** [comment]
> ... then the translated root route is removed and the neutral one gets added but since I am manually removing and adding routes it messes up the order (which I set with Order parameter on attribute routes) and as such certain things break.

Afaik this shouldn't break the order. Can you show me your complete route configuration?

**Comment by brgrz** [comment]
I had an issue with T4MVC messing up my rendering so that is ok now.

I have a general concern about the way RL handles route generation as per AddAsDefaultRoute.

We might have some routes that we need to add as default culture and then localize them and then we might have (actually we have lots of) routes that should always stay neutral.

The ratio in most cases will be a few translatable routes and much more neutral routes.

For example of such neutral routes consider a route that renders a partial view and is used throughout Razor views:

		[Route("{id:int}/partial")]
        public virtual ActionResult Partial(int id, string partialView)
        {
            var model = _repository.Find(id);
            if (model == null)
                return new EmptyResult();

            if (string.IsNullOrWhiteSpace(partialView))
                return PartialView("Slideshow", model);

            return PartialView(partialView, model);
        }

This is broken when using AddAsDefaultRoute because it no longer responds at 

`/25/partial?partialView=SlideshowCustom`

but at

`en/25/partial?partialView=SlideshowCustom`

The problem is, when the calling page is on different culture, it will request per that culture but the route for that culture to render such partial view is missing. Got it?

Now with the methods we discussed here I would have to go manually through all those route and remove the default culture route that RL introduced (as per AddAsDefaultRoute).

Since I mostly have 2-3 translatable routes and 4-6 neutral routes per controller that forces me to a lot of manual coding for handling routes.

We need better handling of both types of routes within a single app. I would do it with attributes on controller actions.

What do you think?

**Comment by Dresel** [comment]
If you have more neutral routes then localized I would say `AddAsNeutralRoute` or `AddAsNeutralRouteAndReplaceByFirstTranslation` (which removes neutral once adding a localized one) should be less manual coding.

You may want to look at the TranslateInitialAttributeRoutes function of Localization.cs. There is no "magic" behind that. If you for example use `AddAsNeutralRoute`, then the Localization class just iterates over all routes and calls AddNeutralTranslation:
    ....
    
    case AttributeRouteProcessing.AddAsNeutralRoute:
    case AttributeRouteProcessing.AddAsNeutralRouteAndReplaceByFirstTranslation:
        // Add existing attribute route as neutral route
        Configuration.LocalizationCollectionRoutes.ForEach(
            route => AddNeutralTranslation((LocalizationCollectionRoute)route.Route));
        break;

    ....

This `TranslateInitialAttributeRoutes` just exists, so that you do not have to call AddNeutralTranslation / AddTranslation for every function by hand.

You could for example use 'AttributeRouteProcessing.None' and translate them all by yourself.

If I understand you correctly, you want to add something like [Neutral] and [DefaultCulture] to all of your routes instead of calling AddTranslation to localize the neutral ones?

**Comment by brgrz** [comment]
"You could for example use 'AttributeRouteProcessing.None' and translate them all by yourself.

If I understand you correctly, you want to add something like [Neutral] and [DefaultCulture] to all of your routes instead of calling AddTranslation to localize the neutral ones?"

Both of these two options could work..i'll give it a try.

**Comment by Dresel** [comment]
Well for option 2 we would have to write the logic for the custom attribute detection logic - this is not implemented (yet).

**Comment by brgrz** [comment]
Yes, custom attributes would be the way to go. Everything else requires too much manual coding. Even if I a use `AddAsNeutralRoute` that still requires 20-30 manual translations for routes that require default translation + custom translations (I have about 10 controllers in my app).

**Comment by brgrz** [comment]
After further investigation I think the whole concept should be changed from doing this 

`routes.MapMvcAttributeRoutes(Localization.LocalizationDirectRouteProvider);`

(replacing the default route provider with RL's one) to rather implement the custom route attributes and specify the custom route provider there.

This would make things more granular and give us options to attach RL's LocalizationDirectRouteProvider to only a few/some routes that we explicitely want.

However, the RouteAttribute is sealed, meaning we have to implement new custom RouteAttributes from scratch (see http://stackoverflow.com/questions/22375336/use-custom-route-handler-with-mvc5-attribute-routing).

Since you created RL and have more insight into how exactly it works, what is your opinion on this?

**Comment by Dresel** [comment]
I wouldn't change or replace the default `[Route]` attribute, but add additionally attributes?

For example you could use the `AddAsDefaultCultureRoute` per default, but add additional `[NeutralOnly]` to routes that should stay as neutral routes.

Instead of calling `TranslateInitialAttributeRoutes` you could do something like this:

    routes.Localization(configuration =>
    {
        configuration.DefaultCulture = defaultCulture;
        configuration.AcceptedCultures = acceptedCultures;

        // Dont use build in initial processing
        configuration.AttributeRouteProcessing = AttributeRouteProcessing.None;
        configuration.AddCultureAsRoutePrefix = true;
        configuration.AddTranslationToSimiliarUrls = true;
    }).Translate(localization =>
    {
        // Foreach intercepted attribute route...
        localization.Configuration.LocalizationCollectionRoutes.ForEach(route =>
        {
            // ... check if its an action level attribute route ...
            if (((bool?)route.Route.DataTokens[RouteDataTokenKeys.TargetIsAction]) == true)
            {
                // Action Level AttributeRoute
                // ... get ActionDescriptor for the underlying route object ...
                var actionDescriptor = ((ActionDescriptor[])route.Route.DataTokens[RouteDataTokenKeys.Actions]).Single();

                if (actionDescriptor.GetCustomAttributes(false).OfType<NeutralOnlyAttribute>().Any())
                {
                    // ... and add as neutral route if custom NeutralOnlyAttribute DOES exists
                    localization.AddNeutralTranslation((LocalizationCollectionRoute)route.Route);
                }
                else
                {
                    // ... and add as default culture route if custom NeutralOnlyAttribute does NOT exists
                    localization.AddTranslation(route.Route.Url(), localization.Configuration.DefaultCulture,
                        (LocalizationCollectionRoute)route.Route);
                }
            }
            else
            {
                // Controller Level AttributeRoute

                // ... and add as default culture route if its an Controller Level AttributeRoute
                localization.AddTranslation(route.Route.Url(), localization.Configuration.DefaultCulture,
                    (LocalizationCollectionRoute)route.Route);
            }
        });

I tested it with the "root" route of the sample project:

    [Route, NeutralOnly]
    public virtual ActionResult Start()
    {
        // Redirect to localized Index
        return RedirectToAction(MVC.Home.Index().AddRouteValues(new { culture = Thread.CurrentThread.CurrentCulture.Name }));
    }

Is that what you had in mind?
