### ISSUE TITLE
Neutral Translation allowing access trough default culture

### ISSUE THREAD

**Issue by mdmoura** [Dresel/RouteLocalization#50]
Hello,

I have the following MVC Route:

    [Route("admin/tags"), HttpGet]
    public virtual ActionResult Admin() { }

I want this route to be neutral, I mean, not translated and without prefix.

The route localization configuration I have is the following:

    RouteTable.Routes.MapMvcAttributeRoutes(Localization.LocalizationDirectRouteProvider);

    RouteTable.Routes.Localization(x => {
        x.AcceptedCultures = new HashSet<String>(new String[] { "en", "pt" });
        x.DefaultCulture = "en";
        x.AttributeRouteProcessing = AttributeRouteProcessing.AddAsDefaultCultureRoute;
        x.AddCultureAsRoutePrefix = true;
        x.AddTranslationToSimiliarUrls = true;
      }).TranslateInitialAttributeRoutes().Translate(z => z.Process());

      CultureSensitiveHttpModule.GetCultureFromHttpContextDelegate = ctx => new CultureInfo("en");

     GlobalFilters.Filters.Add(new CultureSensitiveActionFilterAttribute(true, true));

     RouteTable.Routes.MapRoute("Start", String.Empty, new { controller = "Home", action = "Start" }, new[] { "MVCSite.Controllers"" });
   
And in process extension method I have the following:

    public static void Process(this Localization localization) {
      localization.ForCulture("pt")
        .ForNamedRoute("home.index").AddTranslation("inicio");
      localization.ForController<TagController>().ForAction(x => x.Admin()).AddNeutralTranslation();       
    } // Process

With this I am able to access:
/admin/tags
/en/admin/tags

And not able to access
/pt/admin/tags

However, I shouldn't be able to access 
/en/admin/tags

Only: /admin/tags

No? Am I missing something?

And is there any action attribute to make a route not translated and stay as it is independent of the culture use? I was looking trough the source but didn't find anything.

Thank You

**Comment by Dresel** [comment]
We have a similiar discussion [here] (https://github.com/Dresel/RouteLocalization/issues/46).

At the moment there are no (built-in) way to use custom attributes for route localization but I'm planning to add this to a future version.

You can remove the localised route at the moment with something like this:

    public static RouteTranslator<T> RemoveTranslation<T>(this RouteTranslator<T> localization, string culture)
    {
        var localizationCollectionRoute = localization.GetRoutes().Single();
        localizationCollectionRoute.RemoveTranslation(culture);

        return localization;
    }
