### ISSUE TITLE
No Route found for given Controller 'Account' and Action 'Login'.

### ISSUE THREAD

**Issue by tacud** [Dresel/RouteLocalization#54]
I'm having issues with this code:

**Controller**:

``` c#
[RouteArea("Area.Identity", AreaPrefix = "")]
[RoutePrefix("account")]
[Route("{action}", Name = "Identity.Accounts")]
public class AccountController : Controller
{
    [HttpGet]
    public ActionResult Login(LoginViewRequest request)
    {
        // process request
        return View();
    }

    [HttpPost]
    [ValidateAntiForgeryToken]
    public Task<ActionResult> Login(LoginView data)
    {
        // process data
        return View();
    }
}
```

**Localization Configuration**:

``` c#
routes.LowercaseUrls = true;
routes.MapMvcAttributeRoutes(Localization.LocalizationDirectRouteProvider);
routes.Localization(configuration =>
{
    configuration.DefaultCulture = "en";
    configuration.AcceptedCultures = new HashSet<string>() { "en", "cs" };
    configuration.AttributeRouteProcessing = AttributeRouteProcessing.AddAsNeutralAndDefaultCultureRoute;
    configuration.AddTranslationToSimiliarUrls = true;
}).Translate(localization =>
{
    localization.TranslateInitialAttributeRoutes();
    localization.ForCulture("cs")
        .ForController<AccountController>().SetAreaPrefix("").SetRoutePrefix("ucet")
        .ForAction("Login").AddTranslation("prihlaseni");
});
```

When I try to load the site, I get the error: No Route found for given Controller 'Account' and Action 'Login'. But when I comment out the localization for the AccountController, I'm able to load /account/login page without any problems.

**Comment by Dresel** [comment]
You are specifying an attribute route on controller level (`[Route("{action}", Name = "Identity.Accounts")]`). You can translate [controller level routes](https://github.com/Dresel/RouteLocalization/blob/master/Documentation/SelectingAndTranslatingRoutes.md#adding-controller-level-translations), but you have to use the `{action}` parameter in your translations. Asp.Net uses the action name to distinguish actions for controller level attribute routes, so you have to use "login" for the `{action}` part of your url.

If you want to translate "login", I'm afraid you have to use attribute routing on action level:

    [RouteArea("Area.Identity", AreaPrefix = "")]
    [RoutePrefix("account")]
    public class AccountController : Controller
    {
        [HttpGet]
        [Route("login")]
        public ActionResult Login(LoginViewRequest request)
        {
            // process request
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        [Route("login")]
        public Task<ActionResult> Login(LoginView data)
        {
            // process data
            return View();
        }
    }

**Comment by tacud** [comment]
Hi, thank you for your response. Yes, you're right, it works this way. It's just a little bit "redundant", the route table will grow and it's harder to maintain.

Do you think it would be possible to implement the {action} parameter into your code so that it works with actual Action name and translates it? After all, this parameter is reserved for this purpose, as well as for example {controller}. I know it depends on how exactly your code works. I'm sorry, I haven't examined it.

**Comment by Dresel** [comment]
Yeah I see your problem, but I don't know an easy way how to handle this use case. RouteLocalization just wraps existing attribute routes and allows to add translations (one per language / route) for those existing attribute routes.

The selection of the action is implemented in the controller (base) class of the asp.net core where I have no access to.

So without adding multiple translated non-controller routes (without the {action} parameter) for one controller level attribute route (with {action}) this would not be possible, which would require too much effort of recoding (but it may be feasible with vNext).
