### ISSUE TITLE
Routes without Localization

### ISSUE THREAD

**Issue by JobaDiniz** [Dresel/RouteLocalization#57]
It seems that is not possible to have routes without localization once you add a localization for any route. _(using attribute routing)_

My controller **without** setting up localization for it.

```
[RoutePrefix("payment")]
public class Payment : Controller
{
  [Route("continue/paypal", Name="PaypalRedirect")]
  public ActionResult RedirectPaypal() { ....}
}
```

In my WebApi, I'm trying to build a link to that action:
`var url = Url.Link("PaypalRedirect", null);` However, **url** is alway _null_.

But, once I add a localization for that route, and write `var url = Url.Link("PaypalRedirect", new {culture = "en-US"});` it works, the generated url is right.

How I can fix this?

**Comment by Dresel** [comment]
So if I understand you correctly, you want to generate a neutral (non-localized) route?

Neutral route only exists by default if you use `AddAsNeutralRoute`, `AddAsNeutralAndDefaultCultureRoute` or `AddAsNeutralRouteAndReplaceByFirstTranslation` for `AttributeRouteProcessing`.

If there is no neutral route, you can add it manually via `AddNeutralTranslation`.

    localization.AddNeutralTranslationForNamedRoute("PaypalRedirect");

Does this help / work for you?

**Comment by JobaDiniz** [comment]
`localization.AddNeutralTranslationForNamedRoute("PaypalRedirect");` it worked.
