### ISSUE TITLE
Problem with Link Generation for Route

### ISSUE THREAD

**Issue by Neilski** [Dresel/RouteLocalization#59]
I am not sure if this is an issue, or my incompetence, but I have two Action methods on my home Controller (one for GET and one for POST).  These are defined as follows:

```
[Route("Articles/{id?}/{sid?}"), HttpGet]
public async Task<ActionResult> Articles(string id, string sid)
{
    var model = new MasonryViewModel(id, sid);
    await PopulateMasonryViewModel(model);
    return View("Index", model);
}

[Route("Articles"), HttpPost, ValidateAntiForgeryToken]
public async Task<ActionResult> Articles(MasonryViewModel model)
{
    await PopulateMasonryViewModel(model);
    return View("Index", model);
}
```

I then apply translations to these routes as follows:

```
public static void AddRoutesTranslation(this Localization localization)
{
    // Home/Articles
    localization.ForCulture("fr-FR")
        .ForController<HomeController>()
        .ForAction(ctrl => ctrl.Articles("", ""), new[] {typeof(string), typeof(string)})
        .AddTranslation("~/Articles/{id}/{sid}");

    localization.ForCulture("fr-FR")
        .ForController<HomeController>()
        .ForAction(ctrl => ctrl.Articles(null), new[] {typeof(MasonryViewModel)})
        .AddTranslation("~/Artikels");

    localization.ForCulture("de-DE")
        .ForController<HomeController>()
        .ForAction(ctrl => ctrl.Articles("", ""),
            new[] {typeof(string), typeof(string)})
        .AddTranslation("~/Artikels/{id}/{sid}");

    localization.ForCulture("de-DE")
        .ForController<HomeController>()
        .ForAction(ctrl => ctrl.Articles(null),
            new[] {typeof(MasonryViewModel)})
        .AddTranslation("~/Artikels");
}
```
All appears to work and route correctly, with the exception of the link generation.  If I define a link as follows:

```
@Html.ActionLink("IT and Cloud", "Articles", new {id = "it", sid = "cloud"}, null)
```

The URL that I get is: `/de-de/artikels?id=it&sid=cloud` (with query string) when what I want is: `/de-de/artikels/it/cloud`.

I tried adding the `Order = n` attribute to the two route definitions to priorities the HttpGet Action of the HttpPost action (`[Route("Articles/{id?}/{sid?}"), HttpGet]`).  This resolved the link generation issue, but then the HttpPost failed with a 404 - not found error.  Changing the language from default (en-GB) to German or French does not make any difference.

This is my first project with _RouteLocalization_ and I suspect my problem is in the way I have defined the routes/translations, so any help/guidance would be very much appreciated.  Thank you.

**Comment by Neilski** [comment]
I _think_ I may have resolved this...

1. Add the 'Order = n'  attriubute to each of the  `[Route()]` definitions - priorities the GET over the POST
2. Give the POST route a name - in this case 'ArticlesPost'

```
[Route("Articles/{id?}/{sid?}", Order = 1), HttpGet]
public async Task<ActionResult> Articles(string id, string sid)
{
    var model = new MasonryViewModel(id, sid);
    await PopulateMasonryViewModel(model);
    return View("Index", model);
}

[Route("Articles", Name = "ArticlesPost", Order = 2), HttpPost, ValidateAntiForgeryToken]
public async Task<ActionResult> Articles(MasonryViewModel model)
{
    await PopulateMasonryViewModel(model);
    return View("Index", model);
}
```

3. Finally, change the form submission Razor/HTML to use the 

```
@using (Html.BeginRouteForm("ArticlesPost", FormMethod.Post, null))
{
   ...
}
```

This appears to give me the routes and links that I had wanted.

**Comment by Dresel** [comment]
I think this is more related to Asp.Net MVC routing than to route localization.

The 404 you get is because the form is posted to an invalid url.

Changing the url for the post method to "Articles/{id?}/{sid?}" is not an option? You could then also use [AddTranslationToSimiliarUrls](https://github.com/Dresel/RouteLocalization/blob/master/Documentation/SelectingAndTranslatingRoutes.md#translate-similiar-routes-at-once).

Otherwise I would also go with named routes, as you did.

**Comment by Neilski** [comment]
Thank you.  Yes, I am new to Attribute Routing too as I was prompted to this route(sic) so I could use your excellent library.

Unfortunately, in this case, keeping the method signature for the GET and the POST is not an (easy) option.

Thank you for your hard work on this project - it makes supporting multiple languages and cultures that much easier.
