### ISSUE TITLE
How to route sitemap.xml

### ISSUE THREAD

**Issue by speakertrading** [Dresel/RouteLocalization#63]
Hi

I'm using your library and all is ok except for routing sitemap.xml.

I generate sitemap.xml from my home controller:

        [Route("~/sitemap.xml")]
        public ActionResult SitemapXml()
        {
            string xml = "...";
            return this.Content(xml, "application/xml", Encoding.UTF8);
        }

I try, in RouteConfig, with:

     routes.MapRoute("Sitemap", "sitemap.xml", new { controller = "Home", action = "SitemapXml" });

In other projects run, but using your library fail. If I change "sitemap.xml" for "sitemapxml" (without the dot) all run ok. But I need the url with the dot.

I try set the url in different ways but with no success:

            localization.ForCulture("es")
                .ForController<HomeController>()
                .AddTranslation("~/sitemap.xml", "es", "Home", "SitemapXml", null, null);

How can I resolve this problem?

**Comment by Dresel** [comment]
I don't think this is RouteLocalization specific, see this [issue](https://stackoverflow.com/questions/11728846/dots-in-url-causes-404-with-asp-net-mvc-and-iis/12151501) on stackoverflow.

Try something like

    <handlers>
        <add name="Sitemap"
            path="sitemap.xml"
            verb="GET"
            type="System.Web.Handlers.TransferRequestHandler" />
    </handlers>

**Comment by speakertrading** [comment]
It's true!

I was using that in other project but I forgot completely.

Thnks for your quick response!

Great library, congratulations!
