### ISSUE TITLE
Make route ignore culture parameter

### ISSUE THREAD

**Issue by mdmoura** [Dresel/RouteLocalization#69]
I have the following configuration:

  services
    .AddMvc(x => { x.Filters.Add(new MiddlewareFilterAttribute(typeof(LocalizationPipeline))); })
    .AddTypedRouting()
.AddRouteLocalization(x => {

      x.UseCulture("pt")
        .WhereController(nameof(HomeController))
        .WhereAction(nameof(HomeController.Index))
        .TranslateAction("");		

    x.UseCulture("pt")
        .WhereController(nameof(AboutController))
        .WhereAction(nameof(AboutController.Index))
        .TranslateAction("quem-somos"); 
      
    })          
    .AddViewLocalization(LanguageViewLocationExpanderFormat.Suffix)
    .AddDataAnnotationsLocalization();    

    services.AddSingleton(x => {
        RequestLocalizationOptions requestLocalizationOptions = new RequestLocalizationOptions() {        
           DefaultRequestCulture = new RequestCulture("en"),
           SupportedCultures = new[] { new CultureInfo("en"), new CultureInfo("pt") },
           SupportedUICultures = new[] { new CultureInfo("en"), new CultureInfo("pt") },
        };
        requestLocalizationOptions.RequestCultureProviders.Insert(0, new RouteDataRequestCultureProvider());
        return requestLocalizationOptions;
  });

}

And I have the following route:

      [Route("api")]
      public class BookApiController : Controller {

        [HttpPost("books"), ValidateAntiForgeryToken]
        public async Task<IActionResult> Get([FromBody]BookGetApiModel.Query query) {
        }

     }

Is it possible to make this route being always the same, so ignoring culture parameter?

**Comment by Dresel** [comment]
I don't know if I understood the question. If you do not translate it, it will always stay as defined. If you use generic methods like `WhereUntranslated` or `WhereTranslated` you could add `.Filter<BookApiController>()` to filter specific controller / actions?

**Comment by mdmoura** [comment]
It was a bug on my JS code. I was missing the initial / in routes. It is solved. Thank You.
