### ISSUE TITLE
Controller part is not translated

### ISSUE THREAD

**Issue by speakertrading** [Dresel/RouteLocalization#72]
I have all routes in spanish and support both spanish and english but english urls not translate the controller part.

/es/cuenta/iniciar-sesion <-- works ok
/en/account/login <-- fail
/en/cuenta/login <-- work, but I want /en/account/login

I create a MVC project with Visual Studio and Add RouteLocalization.

In AccountController I add:
RoutePrefix("cuenta") // In controller class
Route("iniciar-sesion") // for login actions

And this is my configuration:

`public static void RegisterRoutes(RouteCollection routes)
{
    routes.IgnoreRoute("{resource}.axd/{*pathInfo}");

    routes.MapMvcAttributeRoutes(Localization.LocalizationDirectRouteProvider);

    var defaultCulture = "es";
    var acceptedCultures = new HashSet<string> { "es", "en" };

    routes.Localization(configuration =>
    {
        configuration.DefaultCulture = defaultCulture;
        configuration.AcceptedCultures = acceptedCultures;
        configuration.AttributeRouteProcessing = AttributeRouteProcessing.AddAsNeutralAndDefaultCultureRoute;
        configuration.AddCultureAsRoutePrefix = true;
        configuration.AddTranslationToSimiliarUrls = true;
    }).TranslateInitialAttributeRoutes().Translate(localization =>
    {
        // NOT WORK!
        //localization.SetRoutePrefix("account");

        // NOT WORK!
        localization.ForCulture("en")
            .ForController<AccountController>()
            .SetRoutePrefix("account");

        var ts = typeof(string);
        localization.AddTranslation("login", "en", "Account", "Login", "RouteLocTest.Controllers", new[] { ts, ts, ts });

        localization.AddTranslation("login", "en", "Account", "Login", "RouteLocTest.Controllers", new[] { typeof(LoginViewModel), ts });
    });

    routes.MapRoute(
        name: "Default",
        url: "{controller}/{action}/{id}",
        defaults: new { controller = "Home", action = "Index", id = UrlParameter.Optional }
    );

    CultureSensitiveHttpModule.GetCultureFromHttpContextDelegate =
        Localization.DetectCultureFromBrowserUserLanguages(acceptedCultures, defaultCulture);

    GlobalFilters.Filters.Add(new CultureSensitiveActionFilterAttribute()
    {
        AcceptedCultures = acceptedCultures,
        TryToPreserverBrowserRegionCulture = true
    });
}
`

**Comment by Dresel** [comment]
You have to make a chained call to `AddTranslation`, otherwise `SetRoutePrefix` does nothing, see [here](https://github.com/Dresel/RouteLocalization/blob/master/Source/RouteLocalization.Mvc.Sample/App_Start/DefaultRoutes.cs).

**Comment by speakertrading** [comment]
Ahhh

I was invoke SetRoutePrefix and AddTranslation in separated sentences. Now is working fine:

`
      localization.SetRoutePrefix(controllerTrans)
           .AddTranslation(url, culture, controller, action, controllerNamespace, types);
`
Thank you!!!

Great job your library
