### ISSUE TITLE
GetRouteData return empty WebAPI route instead valid MVC route

### ISSUE THREAD

**Issue by speakertrading** [Dresel/RouteLocalization#75]
Hello

I have an MVC application with a Web API controller. I'm using RouteLocalization.MVC and RouteLocalization.WebAPI and all works fine. But I need get route from url string and this code fail:

    var httpContext = new RouteUtils.RewritedHttpContextBase("~/Home/About");
    var routeData = RouteTable.Routes.GetRouteData(httpContext);

Returned value has a System.Web.Http.WebHost.Routing.HttpWebRoute route. Values property is empty. If I comment Web API registration, route return expected "Home/About" controller/action. Why I'm getting the WebAPI route with "empty" content instead expected MVC route?

[MyWeb.zip](https://github.com/Dresel/RouteLocalization/files/2284716/MyWeb.zip)

**Comment by Dresel** [comment]
Your httpContext seems to be wrong.

Maybe try this method: https://rockdovedev.wordpress.com/2013/06/05/url-to-route-data/

**Comment by speakertrading** [comment]
Works nice. Thnks Dresel!!
