### ISSUE TITLE
The state of ASP.NET Core branch

### ISSUE THREAD

**Issue by kasparkallas** [Dresel/RouteLocalization#76]
Hey @Dresel 

I am building a simple web application with localized routes and I downloaded the 1.0.0-alpha2 from NuGet.

And... It seems to work great so far! 

So I was wondering what is the hold up for doing a proper release? As the "alpha" is a little bit off putting. And I think the Core version should be moved to a repository of it's own. Is there any way I could help?

**Comment by kasparkallas** [comment]
I would be happy to help out. I'd say I'm medium motivated.

It took me just few minutes to update the packages in the sample project and not that long to be comfortable with the API. Nice logical fluent API. But that's exactly my point -- this deserves a repository of it's own and a non-alpha release. The library is a thin layer on top of ASP.NET Core MVC so I would not be too worried about releasing...

For future developments, I think it should be possible to configure localized routes with attributes. But it's not a big deal -- same functionality, just a different way to organize the code.

**Comment by Dresel** [comment]
Sounds reasonable :)

**Comment by Dresel** [comment]
Moved to https://github.com/Dresel/RouteLocalization.AspNetCore and upgraded to 2.0.

Still have to upgrade CI, and maybe remove unnecessary assets from the sample project and we are good to go for release 1.0.

**Comment by Dresel** [comment]
1.0.0 is publicly available. Feel free to add issues, suggestions (e.g. the attribute localization configuration) or anything else to the new repository.

**Comment by kasparkallas** [comment]
Nice! Good job and thanks, @Dresel!

I will make an effort to contribute.
